#!/usr/bin/env bash

DISPLAY=1

CURRENT=`/usr/local/bin/ddcctl -d $DISPLAY -i \? | grep current | cut -d " " -f8 | cut -d "," -f1`

echo $CURRENT

if [ "$CURRENT" == "15" ]; then
  echo "switching to MDP"
  /usr/local/bin/ddcctl -d 1 -i 16
elif [ "$CURRENT" == "16" ]; then
  echo "switching to DP"
  /usr/local/bin/ddcctl -d 1 -i 15
else
  echo "not familiar with current setting, $CURRENT"
fi

